server:
  port: 8761
spring:
  security:
    user:
      name: user
      password: 123456
  application:
    name: admin-client2
#    日志信息
logging:
  file: ./log/admin-client2.log
eureka:
  instance:
#      leaseRenewalIntervalInSeconds: 10
      health-check-url-path: /actuator/health   #健康检查的地址
      instance-id: admin-client2 #服务中心中该服务的注册名
      prefer-ip-address: true #是否显示IP
#   Eureka 中的 metadataMap 专门用来存放一些自定义的数据，
#   当注册中心或者其他服务需要此服务的某些配置时可以在 metadataMap 里取。
#  实际上，每个 instance 都有各自的 metadataMap，map中存放着需要用到的属性。
#  例如，上面配置中的 eureka.instance.metadata-map.user.name，
#  当这个服务成功注册到 Eureka 上，Spring Boot Admin 就会取拿到这个 instance，
# 进而拿到 metadataMap 里的属性，然后放入请求头，向此服务发送请求，
#访问此服务的 Actuator 开放的端点。
      metadata-map:
        user.name: user  #用户名和密码必须和security下配置的用户名和密码相同，否则启动后服务端是DOWN的状态
        user.password: 123456
  client:
#    registryFetchIntervalSeconds: 5   #服务拉取时间间隔 秒
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:10086}/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
