server:
  port: 10010
spring:
  application:
    name: liujie-gateway
# 日志文件相关配置
logging:
  file: ./log/zuul-gateway.log
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always


zuul:
  prefix: /api # 添加路由前缀
  retryable: true
  routes:
    liujie-service: /liujie/** # 将微服务liujie-service映射到/liujie/**
  ignored-patterns: /upload/**  # 被忽略的路由地址
#ribbon负载均衡
ribbon:
  ConnectTimeout: 250 # 连接超时时间(ms)
  ReadTimeout: 2000 # 通信超时时间(ms)
  OkToRetryOnAllOperations: true # 是否对所有操作重试
  MaxAutoRetriesNextServer: 1 # 同一服务不同实例的重试次数
  MaxAutoRetries: 1 # 同一实例的重试次数
#  hystrix熔断
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 10000 # 熔断超时时长：10000ms